---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      name: Authorization
      scheme: bearer
      type: http
      in: header
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/api/v1/register":
    post:
      summary: create user
      responses:
        '200':
          description: successful
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: 127.0.0.1
