---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearerAuth:
      name: Authorization
      scheme: bearer
      type: http
      in: header
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/api/v1/register":
    post:
      summary: create user
      tags:
      - authentication
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/login":
    post:
      summary: login user
      tags:
      - authentication
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: 127.0.0.1
